//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAMPUS_FIX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint_Master
    {
        public int ComplaintId { get; set; }
        public string FacilityType { get; set; }
        public string Location { get; set; }
        public string IssueDetails { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
    }
}
