//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAMPUS_FIX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComplaintdbEntities : DbContext
    {
        public ComplaintdbEntities()
            : base("name=ComplaintdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Complaint_Master> Complaint_Master { get; set; }
        public virtual DbSet<Enquiry_Master> Enquiry_Master { get; set; }
        public virtual DbSet<login_Master> login_Master { get; set; }
        public virtual DbSet<Notification_Master> Notification_Master { get; set; }
    }
}
