//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAMPUS_FIX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_Master
    {
        public int NotiId { get; set; }
        public string NotiMessage { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    }
}
